### ISSUE TITLE
Table : contest_teamr already exists

### ISSUE THREAD

**Issue by suchandd** [docodon/OJUDGE#1]
suchand@suchand-Lenovo-Z50-70:~/Desktop/OJUDGE-master$ python manage.py migrate
/home/suchand/.local/lib/python2.7/site-packages/django/template/utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

/home/suchand/Desktop/OJUDGE-master/register/urls.py:8: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^logout/$',views.logout_reg,name='logout_reg')

/home/suchand/Desktop/OJUDGE-master/pset/urls.py:15: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^start_contest',views.start_contest,name='start_contest'),

/home/suchand/Desktop/OJUDGE-master/contest/urls.py:11: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^rankings/$',views.rankings,name='rankings'),

/home/suchand/Desktop/OJUDGE-master/OJUDGE/urls.py:9: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^contest/',include('contest.urls')),

/home/suchand/Desktop/OJUDGE-master/OJUDGE/urls.py:20: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  {'document_root': settings.MEDIA_ROOT}),

/home/suchand/.local/lib/python2.7/site-packages/django/conf/urls/**init**.py:89: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got serve). Pass the callable instead.
  t = url(prefix=prefix, *t)

Operations to perform:
  Apply all migrations: sessions, admin, register, auth, contenttypes, contest
Running migrations:
  Rendering model states... DONE
  Applying contest.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/suchand/.local/lib/python2.7/site-packages/django/core/management/**init**.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(_args, *_options)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 284, in create_model
    self.execute(sql, params or None)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/suchand/.local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "contest_teamr" already exists

**Comment by docodon** [comment]
Hey there ! I have used Django-1.7 in the making of ojudge .
It will work in django 1.7 but for  1.10(yours one) definitely changes have to be made .
